### ISSUE TITLE
blank_v3_genome_assemblies example spreadsheet has values in wrong row

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/covid-excel-utils#28]
I noticed that in the spreadsheet `blank_v3_genome_assemblies.xlsx` there are values for 'accepted values' in the 5th row rather than the 4th row.

**Comment by MightyAx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Updated Examples Files](https://trello.com/c/rKZIZsx6/28-updated-examples-files)
